spring:
  config:
    activate:
      on-profile: mock
  datasource:
    url: jdbc:tc:postgresql:9.6.8:///databasename
    username: postgres
    password: mysecretpassword
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

